# Generated by Django 4.1.3 on 2023-09-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_alter_product_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='u_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
