# Generated by Django 4.1.3 on 2023-09-10 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_rename_first_name_customer_u_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='userid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
